export interface AddProduct{
    name: string,
    categoryId: number,
    subCategoryId: number,
    description: string,
    image: string,
    isActive: boolean,
    rank: number,
    modelId: number,
    brandId: number,
    content: string,
    nutritionalValues: string,
    usage: string,
    price: number,
    taxRate: number,
    totalPrice: number,
    totalPriceTl:number,
    cost: number,
    barcode: string,
    unitCount: number,
    unitTypeId: number,
    supplier:number[],
    stockCount:number,
}